name: Upload to SourceForge

on:
  workflow_dispatch:
    inputs:
        DL_LINK:
          description: "Link of the File to Upload"
          required: true
        
        DEVICE_CODENAME:
          description: "Device Codename"
          required: true

defaults:
  run:
    shell: bash

env:
  DOWNLOAD_LINK: ${{ github.event.inputs.DL_LINK }}
  DEVICE: ${{ github.event.inputs.DEVICE_CODENAME }}

  # SourceForge Credentials
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_PASS: ${{ secrets.SF_PASSWORD }}
  SF_PROJECT: raven-os

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts
        uses: actions/checkout@v2

      - name: Download Build
        run: |
          mkdir raven_tmp
          cd raven_tmp
          if [[ $DOWNLOAD_LINK == *"drive.google.com"* ]]; then
          pip install gdown
          if [[ $DOWNLOAD_LINK == *"file"* ]]; then
          download_link=$(echo $download_link | cut -d / -f 6)
          elif [[ $DOWNLOAD_LINK == *"id"* ]]; then
          download_link1=$(echo $DOWNLOAD_LINK | cut -d = -f 2 | cut -d '&' -f 1)
          download_link2=$(echo $DOWNLOAD_LINK | cut -d = -f 4)
          fi
          gdown https://drive.google.com/uc?id=$download_link1 || gdown https://drive.google.com/uc?id=$download_link2
          else
          aria2c -c -m0 -x16 -s50 $DOWNLOAD_LINK
          fi
          cd -

      - name: Upload the Build
        run: |
          sudo apt install sshpass
          sshpass ${SF_PASS} rsync $(ls) ${SF_USERNAME}@frs.sourceforge.net:/home/frs/project/${SF_PROJECT}/${DEVICE}/
